### ISSUE TITLE
APK download

### ISSUE THREAD

**Issue by IzzySoft** [CK1412/note_app_flutter_sqflite_provider#2]
Hi, and thanks for making you app available open-source with a FOSS license! In your Readme you write:

> You can use the app by installing Play Store (applicable to android devices)

What about those who can not (or want not to) have PlayStore on their devices? Would you consider making the APK available here, e.g. attached to the corresponding [release](https://github.com/CK1412/note_app_flutter_sqflite_provider/releases)? Thanks in advance!

**Comment by CK1412** [comment]
Thanks for your feedback, I added the apk file.

**Comment by IzzySoft** [comment]
Thanks a lot! Your app will then become available in my repo with the next sync around 7 pm UTC today and should then [show up here](https://apt.izzysoft.de/fdroid/index/apk/CK1412.com.github.note_app_flutter_sqflite_provider). I've noticed the packageName is different to that at Google Play, was that intended?

**Comment by CK1412** [comment]
Because the package name is quite long, I shortened it, please use the same package name as on google play

**Comment by IzzySoft** [comment]
I cannot change the package name, that's set in the APK:

```
package: name='CK1412.com.github.note_app_flutter_sqflite_provider' versionCode='1001' versionName='1.0.0' platformBuildVersionName='11' platformBuildVersionCode='30' compileSdkVersion='30' compileSdkVersionCodename='11'
```

So you need to set it there, ideally to the same one you use on Play. If you have a new APK with the correct packageName so I can replace it before 6 pm UTC, we can start with the right one straight ahead.

**Comment by CK1412** [comment]
I have fixed packageName and release v1.0.1

**Comment by CK1412** [comment]
Please use latest version

**Comment by IzzySoft** [comment]
Thanks! Replaced. Please make sure that future releases have their `versionName` and `versionCode` fixed: currently, the APK attached to v1.0.2 identifies as `package: name='github.ck1412.noteApp' versionCode='1001' versionName='1.0.0'` which leads to a loop in my updater which thinks it has v1.0.0 and sees the v1.0.2 tag expecting a new version, getting the same APK, throwing it away – and that every day. Let me know when a fixed tag is there, so I can re-enable the "daily updater" (I've set it to monthly now to avoid the loop and giving you some time for the next release :wink:)

Oh, and with the name fixed your app of course will show up under the [proper new URL](https://apt.izzysoft.de/fdroid/index/apk/github.ck1412.noteApp) in about 2 hours from now :smile: Be welcome to [pick a badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) if you want to link there e.g. from your Readme here.

**Comment by CK1412** [comment]
I forgot, version name will be updated next time. About the updater, please keep it updated every month.

**Comment by IzzySoft** [comment]
I will! If you drop me a note when the next "proper release" is there, I can switch the check back to daily.

**Comment by IzzySoft** [comment]
It's live now! :star_struck:
